import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { FiArrowLeft, FiShield, FiChevronDown, FiChevronUp } from "react-icons/fi";

const sections = [
  {
    id: "interpretation",
    title: "Interpretation and Definitions",
    icon: "📖",
    subsections: [
      {
        title: "Interpretation",
        content:
          "The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
      },
      {
        title: "Definitions",
        content: null,
        definitions: [
          { term: "Account", def: "A unique account created for You to access our Service or parts of our Service." },
          { term: "Affiliate", def: 'An entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.' },
          { term: "Company", def: 'Referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy — refers to Last Digit Lotto.' },
          { term: "Cookies", def: "Small files placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses." },
          { term: "Country", def: "Delhi, India" },
          { term: "Device", def: "Any device that can access the Service such as a computer, a cell phone or a digital tablet." },
          { term: "Personal Data", def: 'Any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.' },
          { term: "Service", def: "Refers to the Website." },
          { term: "Service Provider", def: "Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service." },
          { term: "Usage Data", def: "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
          { term: "Website", def: "Last Digit Lotto, accessible from https://lastdigitlotto.in/" },
          { term: "You", def: "The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." },
        ],
      },
    ],
  },
  {
    id: "collecting",
    title: "Collecting and Using Your Personal Data",
    icon: "🗂️",
    subsections: [
      {
        title: "Types of Data Collected",
        content:
          "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Usage Data is collected automatically when using the Service and may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
      },
      {
        title: "Tracking Technologies and Cookies",
        content:
          "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. We use both Session and Persistent Cookies. Necessary/Essential Cookies are essential to provide You with services available through the Website. Functionality Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.",
      },
      {
        title: "Use of Your Personal Data",
        content: null,
        list: [
          "To provide and maintain our Service, including to monitor the usage of our Service.",
          "To manage Your Account and registration as a user of the Service.",
          "For the performance of a contract — the development, compliance and undertaking of the purchase contract.",
          "To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.",
          "To provide You with news, special offers, and general information about other goods, services and events.",
          "To manage Your requests and attend to them.",
          "For business transfers — to evaluate or conduct a merger, divestiture, restructuring, reorganization, or dissolution.",
          "For other purposes such as data analysis, identifying usage trends, and improving our Service.",
        ],
      },
      {
        title: "Sharing Your Personal Data",
        content: null,
        list: [
          "With Service Providers to monitor and analyze the use of our Service.",
          "For business transfers — during negotiations of any merger, sale of Company assets, or acquisition.",
          "With Affiliates, requiring those affiliates to honor this Privacy Policy.",
          "With business partners to offer You certain products, services or promotions.",
          "With other users in public areas of the Service, if applicable.",
          "With Your consent for any other purpose.",
        ],
      },
    ],
  },
  {
    id: "retention",
    title: "Retention of Your Personal Data",
    icon: "🗄️",
    subsections: [
      {
        title: "Retention Periods",
        content:
          "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.",
        list: [
          "Account Information: retained for the duration of your account plus up to 24 months after account closure.",
          "Website analytics data (cookies, IP addresses): up to 24 months from date of collection.",
          "Server logs (IP addresses, access times): up to 24 months for security monitoring.",
        ],
      },
      {
        title: "Data Deletion Procedures",
        content: "When retention periods expire, We securely delete or anonymize Personal Data through:",
        list: [
          "Deletion: Personal Data is removed from Our systems and no longer actively processed.",
          "Backup retention: Residual copies may remain in encrypted backups for a limited period.",
          "Anonymization: In some cases, We convert Personal Data into anonymous statistical data that cannot be linked back to You.",
        ],
      },
    ],
  },
  {
    id: "transfer",
    title: "Transfer of Your Personal Data",
    icon: "🌐",
    subsections: [
      {
        title: "International Transfers",
        content:
          "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. This information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.",
      },
    ],
  },
  {
    id: "delete",
    title: "Delete Your Personal Data",
    icon: "🗑️",
    subsections: [
      {
        title: "Your Right to Delete",
        content:
          "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us. Please note that We may need to retain certain information when we have a legal obligation or lawful basis to do so.",
      },
    ],
  },
  {
    id: "disclosure",
    title: "Disclosure of Your Personal Data",
    icon: "📢",
    subsections: [
      {
        title: "Business Transactions",
        content:
          "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.",
      },
      {
        title: "Law Enforcement",
        content:
          "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
      },
      {
        title: "Other Legal Requirements",
        content: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
        list: [
          "Comply with a legal obligation",
          "Protect and defend the rights or property of the Company",
          "Prevent or investigate possible wrongdoing in connection with the Service",
          "Protect the personal safety of Users of the Service or the public",
          "Protect against legal liability",
        ],
      },
    ],
  },
  {
    id: "security",
    title: "Security of Your Personal Data",
    icon: "🔒",
    subsections: [
      {
        title: "Our Security Commitment",
        content:
          "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.",
      },
    ],
  },
  {
    id: "children",
    title: "Children's Privacy",
    icon: "👶",
    subsections: [
      {
        title: "Age Restrictions",
        content:
          "Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.",
      },
    ],
  },
  {
    id: "links",
    title: "Links to Other Websites",
    icon: "🔗",
    subsections: [
      {
        title: "Third-Party Links",
        content:
          "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
      },
    ],
  },
  {
    id: "changes",
    title: "Changes to this Privacy Policy",
    icon: "📝",
    subsections: [
      {
        title: "Policy Updates",
        content:
          "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the \"Last updated\" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.",
      },
    ],
  },
  {
    id: "contact",
    title: "Contact Us",
    icon: "✉️",
    subsections: [
      {
        title: "Get in Touch",
        content: "If you have any questions about this Privacy Policy, You can contact us by visiting:",
        link: { label: "https://lastdigitlotto.in/profile", href: "https://lastdigitlotto.in/profile" },
      },
    ],
  },
];

function AccordionSection({ section }) {
  const [open, setOpen] = useState(false);

  return (
    <div
      style={{
        background: "#fff",
        borderRadius: 16,
        marginBottom: 12,
        boxShadow: open
          ? "0 4px 24px rgba(220,38,38,0.10)"
          : "0 2px 8px rgba(0,0,0,0.05)",
        border: open ? "1.5px solid #fca5a5" : "1.5px solid #f3f4f6",
        overflow: "hidden",
        transition: "box-shadow 0.2s, border-color 0.2s",
      }}
    >
      {/* Header */}
      <button
        onClick={() => setOpen((v) => !v)}
        style={{
          width: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "16px 18px",
          background: "none",
          border: "none",
          cursor: "pointer",
          textAlign: "left",
          gap: 12,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div
            style={{
              width: 40,
              height: 40,
              borderRadius: 12,
              background: open
                ? "linear-gradient(135deg,#fee2e2,#fecaca)"
                : "#f9fafb",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: 20,
              flexShrink: 0,
              transition: "background 0.2s",
            }}
          >
            {section.icon}
          </div>
          <span
            style={{
              fontWeight: 800,
              fontSize: 14,
              color: open ? "#dc2626" : "#111827",
              transition: "color 0.2s",
              lineHeight: 1.3,
            }}
          >
            {section.title}
          </span>
        </div>
        <div style={{ flexShrink: 0, color: open ? "#dc2626" : "#9ca3af" }}>
          {open ? <FiChevronUp size={18} /> : <FiChevronDown size={18} />}
        </div>
      </button>

      {/* Body */}
      {open && (
        <div style={{ padding: "0 18px 18px" }}>
          <div style={{ height: 1, background: "#f3f4f6", marginBottom: 16 }} />
          {section.subsections.map((sub, si) => (
            <div key={si} style={{ marginBottom: si < section.subsections.length - 1 ? 20 : 0 }}>
              {section.subsections.length > 1 && (
                <p
                  style={{
                    fontWeight: 700,
                    fontSize: 13,
                    color: "#374151",
                    marginBottom: 8,
                    display: "flex",
                    alignItems: "center",
                    gap: 6,
                  }}
                >
                  <span
                    style={{
                      display: "inline-block",
                      width: 4,
                      height: 4,
                      borderRadius: "50%",
                      background: "#dc2626",
                    }}
                  />
                  {sub.title}
                </p>
              )}

              {sub.content && (
                <p style={{ fontSize: 13, color: "#6b7280", lineHeight: 1.7, marginBottom: sub.list || sub.definitions ? 10 : 0 }}>
                  {sub.content}
                </p>
              )}

              {sub.definitions && (
                <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                  {sub.definitions.map((d, di) => (
                    <div
                      key={di}
                      style={{
                        background: "#f9fafb",
                        borderRadius: 10,
                        padding: "10px 12px",
                        borderLeft: "3px solid #fca5a5",
                      }}
                    >
                      <span style={{ fontWeight: 700, fontSize: 12, color: "#dc2626" }}>{d.term}: </span>
                      <span style={{ fontSize: 12, color: "#6b7280", lineHeight: 1.6 }}>{d.def}</span>
                    </div>
                  ))}
                </div>
              )}

              {sub.list && (
                <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 6 }}>
                  {sub.list.map((item, li) => (
                    <li
                      key={li}
                      style={{
                        display: "flex",
                        alignItems: "flex-start",
                        gap: 8,
                        fontSize: 13,
                        color: "#6b7280",
                        lineHeight: 1.6,
                      }}
                    >
                      <span
                        style={{
                          marginTop: 7,
                          width: 5,
                          height: 5,
                          borderRadius: "50%",
                          background: "#dc2626",
                          flexShrink: 0,
                        }}
                      />
                      {item}
                    </li>
                  ))}
                </ul>
              )}

              {sub.link && (
                <a
                  href={sub.link.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: 6,
                    marginTop: 8,
                    fontSize: 13,
                    color: "#dc2626",
                    fontWeight: 600,
                    textDecoration: "none",
                    wordBreak: "break-all",
                  }}
                >
                  🔗 {sub.link.label}
                </a>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default function PrivacyPolicy() {
  const navigate = useNavigate();

  return (
    <div style={{ minHeight: "100vh", background: "#f4f5fb", paddingBottom: 32 }}>
      {/* ── Hero Header ── */}
      <div
        style={{
          position: "relative",
          background: "linear-gradient(135deg, #dc2626 0%, #b91c1c 45%, #7c3aed 100%)",
          padding: "20px 20px 20px",
          overflow: "hidden",
        }}
      >
        {/* decorative circles */}
        <div style={{ position: "absolute", top: -30, right: -30, width: 120, height: 120, borderRadius: "50%", background: "rgba(255,255,255,0.08)" }} />
        <div style={{ position: "absolute", bottom: -20, left: -20, width: 90, height: 90, borderRadius: "50%", background: "rgba(255,255,255,0.06)" }} />
        <div style={{ position: "absolute", top: 12, left: "40%", width: 6, height: 6, borderRadius: "50%", background: "rgba(255,255,255,0.4)" }} />
        <div style={{ position: "absolute", top: 28, right: "30%", width: 4, height: 4, borderRadius: "50%", background: "rgba(253,224,71,0.6)" }} />

        {/* Back button */}
        <button
          onClick={() => navigate(-1)}
          style={{
            display: "flex",
            alignItems: "center",
            gap: 6,
            background: "rgba(255,255,255,0.15)",
            border: "none",
            borderRadius: 12,
            padding: "8px 14px",
            color: "#fff",
            fontSize: 13,
            fontWeight: 700,
            cursor: "pointer",
            marginBottom: 24,
            backdropFilter: "blur(8px)",
          }}
        >
          <FiArrowLeft size={16} /> Back
        </button>

        {/* Title */}
        <div style={{ display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center", position: "relative" }}>
          <div
            style={{
              width: 64,
              height: 64,
              borderRadius: 20,
              background: "rgba(255,255,255,0.15)",
              backdropFilter: "blur(10px)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              marginBottom: 14,
              border: "1.5px solid rgba(255,255,255,0.25)",
            }}
          >
            <FiShield size={28} color="#fff" />
          </div>
          <h1 style={{ fontSize: 24, fontWeight: 900, color: "#fff", margin: 0, letterSpacing: -0.5 }}>
            Privacy Policy
          </h1>
          <p style={{ fontSize: 12, color: "rgba(255,255,255,0.75)", margin: "6px 0 0", fontWeight: 500 }}>
            Last updated: May 22, 2026
          </p>
        </div>
      </div>

      {/* ── Intro Card ── */}
      <div style={{ padding: "0 16px", marginTop: 24 }}>
        <div
          style={{
            background: "#fff",
            borderRadius: 20,
            padding: "18px 18px",
            boxShadow: "0 8px 32px rgba(0,0,0,0.10)",
            marginBottom: 16,
            border: "1.5px solid #f3f4f6",
          }}
        >
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 6,
              background: "#fee2e2",
              borderRadius: 8,
              padding: "4px 10px",
              marginBottom: 10,
            }}
          >
            <span style={{ fontSize: 11, fontWeight: 800, color: "#dc2626", textTransform: "uppercase", letterSpacing: 0.5 }}>
              🛡️ Your Privacy Matters
            </span>
          </div>
          <p style={{ fontSize: 13, color: "#4b5563", lineHeight: 1.75, margin: 0 }}>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service — and tells You about Your privacy rights and how the law protects You.
          </p>
          <p style={{ fontSize: 13, color: "#4b5563", lineHeight: 1.75, margin: "10px 0 0" }}>
            We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>
        </div>

        {/* ── Quick Stats ── */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr 1fr",
            gap: 10,
            marginBottom: 16,
          }}
        >
          {[
            { emoji: "🔒", label: "Encrypted", sub: "Data secured" },
            { emoji: "🚫", label: "No Spam", sub: "Zero ads sold" },
            { emoji: "📋", label: "GDPR", sub: "Compliant" },
          ].map((stat, i) => (
            <div
              key={i}
              style={{
                background: "#fff",
                borderRadius: 14,
                padding: "14px 8px",
                textAlign: "center",
                boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
                border: "1.5px solid #f3f4f6",
              }}
            >
              <div style={{ fontSize: 22, marginBottom: 4 }}>{stat.emoji}</div>
              <p style={{ fontSize: 12, fontWeight: 800, color: "#111827", margin: 0 }}>{stat.label}</p>
              <p style={{ fontSize: 10, color: "#9ca3af", fontWeight: 500, margin: "2px 0 0" }}>{stat.sub}</p>
            </div>
          ))}
        </div>

        {/* ── Section Label ── */}
        <p style={{ fontSize: 11, fontWeight: 800, color: "#9ca3af", textTransform: "uppercase", letterSpacing: 1, marginBottom: 10, paddingLeft: 4 }}>
          Policy Sections — Tap to expand
        </p>

        {/* ── Accordion Sections ── */}
        {sections.map((section) => (
          <AccordionSection key={section.id} section={section} />
        ))}

        {/* ── Footer Note ── */}
        <div
          style={{
            marginTop: 8,
            background: "linear-gradient(135deg,#fee2e2,#fdf4ff)",
            borderRadius: 16,
            padding: "16px 18px",
            border: "1.5px solid #fecaca",
            textAlign: "center",
          }}
        >
          {/* <p style={{ fontSize: 12, color: "#6b7280", margin: 0, lineHeight: 1.7 }}>
            Questions about our privacy practices?{" "}
            <a
              href="https://lastdigitlotto.in/profile"
              style={{ color: "#dc2626", fontWeight: 700, textDecoration: "none" }}
            >
              Contact us →
            </a>
          </p> */}
        </div>
      </div>
    </div>
  );
}
